dashevo/js-drive

.travis.yml
bin/build_docker_images.sh

* Use "set -x" to show script commands in output
* Update image name to dashpay/drive
* Remove ECR authentication and REPO_URL
* Add Docker Hub auth

Deploy Docker image to Docker Hub

---

bin/build_docker_images.sh

This should fix the Docker build

Remove REPO_URL from Docker build script

---

package-lock.json
package.json

https://travis-ci.com/dashevo/drive/builds/109844602#L1256

Fix `dapi-client` sub dependency

---

package-lock.json
package.json

As per [this message](https://github.com/Automattic/mongoose/issues/8180#issuecomment-542848174)

Update `MongoDB` driver

---

.env.example
lib/app/UpdateStateApp.js
lib/app/UpdateStateAppOptions.js
lib/dpp/DriveDataProvider.js
lib/test/registerUser.js
package-lock.json
package.json

Fix updateStateApp
Bump version

fix: user registration and updateStateApp

---

package-lock.json
package.json

Update dependencies
Bump version to 0.7.0-dev.9

chore: bump version to 0.7.0-dev.9

---

package-lock.json
package.json

chore: update dpp version

---

.travis.yml
package-lock.json
package.json

Before merge we should run `npm i` to update `package-lock`.

chore: prepare for release

---

.env.example
lib/createDIContainer.js
package-lock.json
package.json

Update DPP in order to use `skipAssetLockConfirmation`.
More details:  https://github.com/dashevo/js-dpp/pull/184
- Updated to DPP 0.13.0-dev.8
- Renamed `IDENTITY_ENABLE_ASSET_LOCK_TX_ONE_BLOCK_CONFIRMATION_FALLBACK` to `IDENTITY_SKIP_ASSET_LOCK_CONFIRMATION_VALIDATION` 
Not tested. Theoretically should work.
See https://github.com/dashevo/js-dpp/pull/184

feat!: update to DPP 0.13.0-dev.8

---

lib/abci/errors/wrapInErrorHandlerFactory.js
lib/createDIContainer.js
test/unit/abci/errors/wrapInErrorHandlerFactory.spec.js

internal errors lead to inability to fix bugs as it leads state inconsistency
- special flag was added to not catch internal errors in particular cases
Unit test.
None.

fix: internal errors lead to inability to fix bugs as it leads state inconsistency

---

CHANGELOG.md
package-lock.json
package.json

update to 0.13.2
update to 0.13.2

chore: update to 0.13.2

---

package-lock.json
package.json

Updated `dpp` to `0.14.0-dev.4`
Updated `dpp` to `0.14.0-dev.4`
Tests.
None.

feat: update dpp to `0.14.0-dev.4`

---

.travis.yml

To have more consistent testing we need to have an opportunity to use SDK from a particular branch
Changed Travis script
Travis builds
None

 build: install SDK from branch in travis

---

README.md

Brings readme into [standard-readme](https://github.com/RichardLitt/standard-readme) compliance
Minor formatting/link updates. Badges added/updated.
N/A
N/A

docs: update for readme standard compliance, add/fix badges and link

---

package-lock.json
package.json

Update DPP to 0.15.0-dev.14
DPP updated to 0.15.0-dev.14
With tests
See DPP 0.15.0-dev.14 breaking changes.

feat: update DPP to 0.15.0-dev.14

---

lib/dpp/CachedStateRepositoryDecorator.js
lib/dpp/DriveStateRepository.js
test/unit/dpp/CachedStateRepositoryDecorator.spec.js
test/unit/dpp/DriveStateRepository.spec.js

As per new identity DIP we need a method to retrieve identity id by any public key hash
Added `DriveStateRepository#fetchIdentityIdsByPublicKeys` method
None.

feat: implement `fetchIdentityIdsByPublicKeys` method

---

lib/dpp/CachedStateRepositoryDecorator.js
lib/dpp/DriveStateRepository.js
test/unit/dpp/CachedStateRepositoryDecorator.spec.js
test/unit/dpp/DriveStateRepository.spec.js

Implemented batch method `storeIdentityIdPublicKeys`
Implemented batch method `storeIdentityIdPublicKeys`
Unit tests.
None.

feat: implement `storeIdentityPublicKeyHashes` method

---

lib/abci/handlers/query/identitiesByPublicKeyHashesQueryHandlerFactory.js
lib/abci/handlers/query/identityIdsByPublicKeyHashesQueryHandlerFactory.js
lib/createDIContainer.js
lib/dpp/DriveStateRepository.js
scripts/abci.js
test/unit/abci/handlers/query/identitiesByPublicKeyHashesQueryHandlerFactory.spec.js
test/unit/abci/handlers/query/identityIdsByPublicKeyHashesQueryHandlerFactory.spec.js
test/unit/dpp/DriveStateRepository.spec.js

Adding method to get multiple `identity` and its ids by multiple public key hashes.
Added method to get multiple `identity` and its ids by multiple public key hashes.
Unit tests.
None.

feat: implement getting identities by multiple public keys hashes

---

package-lock.json
package.json

To make a new pre-release we need to bump version
Bumped version
Unit tests
None

chore: bump version to 0.16.0-dev.2

---

lib/abci/handlers/deliverTxHandlerFactory.js

Incorrect deliver state transition hash logging
Fixed deliver state transition hash logging
No

fix: incorrect deliver state transition hash logging

---

lib/merkDb/MerkDbInMemoryDecorator.js
test/unit/merkDb/MerkDbInMemoryDecorator.spec.js

See https://github.com/nomic-io/merk/blob/f6c4024c5bae3f0400d965aaf058e76aa94162b8/src/merk/mod.rs#L122
Sort keys before putting or removing them in MerkDB
Tests
No

feat: sort keys for MerkDB

---

lib/createDIContainer.js
lib/test/createTestDIContainer.js
test/integration/merkDb/MerkDbStore.spec.js

chore: use `close` and `destroy` methods

---

lib/document/DocumentsDbTransaction.js
test/unit/document/DocumentsDbTransaction.spec.js

documents DB transaction is already started error
Fixed documents DB transaction is already started error
Unit test aded
No

fix: documents DB transaction is already started error

---

.travis.yml

Build of `node-merk` happening inside of the `Debian` container with `glibc` of version `2.28`, but `bionic` have `glibc` of version `2.27`

chore: update Ubuntu version to support higher version of glibc

---

.travis.yml

Updated `Docker` package name in `Travis` config file

chore: update docker installation for Ubuntu 20.04

---

lib/abci/handlers/query/identitiesByPublicKeyHashesQueryHandlerFactory.js
test/unit/abci/handlers/query/identitiesByPublicKeyHashesQueryHandlerFactory.spec.js

provide proofs for getIdentitiesByPublicKeyHashes endpoint
provided proofs for getIdentitiesByPublicKeyHashes endpoint
Tests
No

feat: provide proofs for getIdentitiesByPublicKeyHashes endpoint

---

package-lock.json

chore: update node-merk

---

lib/abci/handlers/query/dataContractQueryHandlerFactory.js
test/unit/abci/handlers/query/dataContractQueryHandlerFactory.spec.js

Provide proofs for getDataContract endpoint
Added proofs for getDataContract endpoint
Tests
No

feat: provide proofs for getDataContract endpoint

---

lib/abci/handlers/query/documentQueryHandlerFactory.js
test/unit/abci/handlers/query/documentQueryHandlerFactory.spec.js

Provide proofs for getDataContract endpoint
Provided proofs for getDataContract endpoint
Tests
No

feat: provide proofs for getDocuments endpoint

---

.env.example
lib/blockExecution/BlockExecutionStoreTransactions.js
lib/blockExecution/PreviousBlockExecutionStoreTransactionsRepository.js
lib/createDIContainer.js
lib/dpp/CachedStateRepositoryDecorator.js
lib/dpp/DriveStateRepository.js
lib/dpp/LoggedStateRepositoryDecorator.js
lib/identity/SpentAssetLockTransactionsRepository.js
lib/identity/SpentAssetLockTransactionsStoreRootTreeLeaf.js
test/unit/identity/SpentAssetLockTransactionsRepository.spec.js

Added new repository for spent asset lock transactions
Added `SpentAssetLockTransactionsRepository` and updated all it's dependencies  such as `rootTree`.
Added `storeAssetLockTransactionOutPoint` and `checkAssetLockTransactionOutPointExists` methods to `DriveStateRepository`
Unit tests.
None.

feat: add spent asset lock transactions tree

---

lib/abci/handlers/beginBlockHandlerFactory.js
lib/abci/handlers/endBlockHandlerFactory.js

Update code to work with tenderdash
With mn bootstrap
Will not work with tendermint

feat!: update for tenderdash

---

package-lock.json
package.json

bump version to 0.17.0-dev.3
bump version to 0.17.0-dev.3

chore: bump version to 0.17.0-dev.3

---

package-lock.json
package.json

Fixing issue with `ChainLock.blockHash` being little endian
Updated `dashcore-lib`
None.

feat: update dashcore-lib

---

lib/core/ZmqClient.js
lib/core/waitForCoreChainLockSyncFactory.js
package-lock.json
package.json
test/unit/core/waitForCoreChainLockSyncFactory.spec.js

Updated `dashcore-lib` to be able to handle `rawchainlocksig` ZMQ event
- updated `dashcore-lib`
- we now listen to `rawchainlocksig` instead of `rawchainlock`
Unit tests.
None.

feat: update `dashcore-lib` to be able to handle `rawchainlocksig`

---

lib/createDIContainer.js
lib/dpp/CachedStateRepositoryDecorator.js
lib/dpp/DriveStateRepository.js
test/unit/dpp/DriveStateRepository.spec.js

Implement `DriveStateRepository#fetchSMLStore` for asset lock proof verification.
Implemented `DriveStateRepository#fetchSMLStore`
With tests
None

feat: implement `DriveStateRepository#fetchSMLStore`

---

package-lock.json
package.json

chore(release): bump version to 0.17.0-dev.9

---

lib/abci/handlers/query/getProofsQueryHandlerFactory.js
lib/createDIContainer.js
test/unit/abci/handlers/query/getProofsQueryHandlerFactory.spec.js

Implement `getPoofs` abci query for `brodcastTransactionAsync` in DAPI
- Added new factory `getPoofsQueryHandlerFactory`;
- Added new method `getPoofsQueryHandler`;
- Registered method in DI container and add a rout for it;
- Added unit tests
Through new unit tests
None

feat: get proofs ABCI query

---

lib/abci/handlers/deliverTxHandlerFactory.js
lib/core/waitForCoreChainLockSyncFactory.js

Log rawChainLockMessage data on errors
Handle ChainLockSigMessage errors
No

feat: log rawChainLockMessage on errors

---

lib/createDIContainer.js

`trace` and `debug` log levels are not present in log streams despite log level stream settings
Set global log level to `trace`
None
None

fix: only info level logs are present

---

package-lock.json
package.json
scripts/abci.js

Use different handlers for server's handler error and client's connection error.
- Updated `js-abci`
- Updated error handlers
None.

feat: use different handler for ABCI connection error

---

.env.example
lib/core/waitForCoreChainLockSyncFactory.js
lib/core/waitForCoreChainLockSyncFallbackFactory.js
lib/createDIContainer.js
lib/dpp/LoggedStateRepositoryDecorator.js
scripts/abci.js

Trace log level produce too much logs.
- Added `LOG_STATE_REPOSITORY` option. `false` by default.
- Added `LOG_MERK` option. `false` by default.
With tests
None

feat: disable state repository and merk logging by default

---

package-lock.json
package.json

To make a new pre-release we need to bump version
Bumped version
Unit tests
None

chore: bump version to 0.18.0-dev.4

---

.env.example
lib/createDIContainer.js

Adding `driveVersion` to every log output to distinct different version in ELK
- created global child logger with drive version
Local runs
None

feat: add `driveVersion` to every log output

---

lib/createDIContainer.js

To be sure that JSON logs are written on crash
- added disposer to a JSON file stream
Local runs
None

feat: await Node logger stream to be ended

---

lib/abci/errors/wrapInErrorHandlerFactory.js
lib/abci/handlers/beginBlockHandlerFactory.js
lib/abci/handlers/commitHandlerFactory.js
lib/abci/handlers/deliverTxHandlerFactory.js
lib/abci/handlers/errors/DataCorruptedError.js
lib/abci/handlers/infoHandlerFactory.js
lib/abci/handlers/initChainHandlerFactory.js
lib/abci/handlers/stateTransition/unserializeStateTransitionFactory.js
lib/core/waitForCoreChainLockSyncFactory.js
lib/creditsDistributionPool/CreditsDistributionPoolCommonStoreRepository.js
lib/dpp/LoggedStateRepositoryDecorator.js
lib/errorHandlerFactory.js
lib/merkDb/MerkDbStore.js
package-lock.json
package.json
scripts/abci.js
test/unit/abci/handlers/stateTransition/unserializeStateTransitionFactory.spec.js
test/unit/dpp/LoggedStateRepositoryDecorator.spec.js
test/unit/util/errorHandlerFactory.spec.js

Adding a lot of top-level fields to JSON logs leads to a mess in Elastic indices (ELK).
- Log receiving kill signal and gracefully shutdown
- Update log contexts to be more distinguished
- Remove unnecessary logs
With tests
None

feat: distinguishing log data

---

lib/abci/closeAbciServerFactory.js
lib/createDIContainer.js
lib/errorHandlerFactory.js
scripts/abci.js
test/unit/abci/closeAbciServerFactory.spec.js
test/unit/util/errorHandlerFactory.spec.js

- Error during error handling produces an infinite loop
- ABCI server continues to accept new connections during the shutdown
- Handle errors thrown from error handler
- Handle multi error handler calls
- Wait until all ABCI connections will be closed before the container disposing and exit
With unit test and running drive with errors
None

feat: robust error handling

---

package-lock.json
package.json
scripts/abci.js

ABCI server doesn't close connection on server close
Update ABCI server to 0.18.6
- Running a node
- Broadcast many STs to increase load
- Restart randomly to  make sure the node stopped gracefully
None

feat: reimplemented ABCI server for better reliability

---

package-lock.json
package.json

chore: bump version to 0.18.0-dev.7

---

.travis.yml
README.md
test/integration/core/updateSimplifiedMasternodeListFactory.spec.js

Do not run node setup if `SKIP_TEST_SUITE` option is set
- Updated `.travis.yml`
None

feat: do not setup node if SKIP_TEST_SUITE option is set

---

Dockerfile
docker/cache/.cache/.gitignore
docker/cache/.npm/.gitignore

To speed up repeated Docker builds we should be able to provide npm and node gyp cache.
- Add npm and node-gyp cache dirs
With running docker build
None

feat: enable docker build npm cache

---

Dockerfile

Docker image not starting because of the missed shared library libzmq.so.5
Fixed Dockerfile

fix: error loading shared library libzmq.so.5

---

lib/abci/handlers/query/documentQueryHandlerFactory.js
test/unit/abci/handlers/query/documentQueryHandlerFactory.spec.js

cannot read property 'getSync' of null error
Added additional check for previous transaction
Unit tests
No

fix: cannot read property 'getSync' of null error

---

package-lock.json
package.json

js-dp-services-ctl updated o 0.19-dev
Tests
No

chore: update js-dp-services-ctl to 0.19-dev

---

lib/dpp/DriveStateRepository.js
test/unit/dpp/DriveStateRepository.spec.js

To support both previous data validated with SML store-based instant lock signature verification we need to bring this logic back to enable a new one with feature flags.
- Commented out a new RPC-based verification logic and tests
- Bring back SML-based instant lock signature validation
With tests
None

chore: verify instant lock with SML store

---

scripts/abci.js

For debugging purposes it will be useful to know current core network 
- Log core network on start
None
None

feat: log Core network on start

---

package-lock.json
package.json
test/integration/abci/handlers/queryHandlerFactory.spec.js
test/integration/blockExecution/PreviousBlockExecutionStoreTransactionsRepository.spec.js

Validation of Identity Create Transition with fake instalock on local network produces the error "Cannot read property 'quorum' of undefined".
- Updated dashcore-lib to new version with fixed `InstantLock#verify` method.
None
None

fix: cannot read property 'quorum' of undefined

---

.github/workflows/test_and_release.yml

Minor fixes
- fix typo
- remove unnecessary input

fix: typo and unnecessary input

---

.github/workflows/test_and_release.yml

`sdk-install` input was inconsistent with other steps
Rename `sdk-install` to `sdk-branch` for consistency
With CI
None

chore(ci): rename sdk-install to sdk-branch

---

package-lock.json
package.json

js-abci wasn't using the patched version of protobuf. This pull request updates js-abci to a version with a patched protobuf to be consistent with the other platform components and to avoid possible inconsistencies with data serialization
Also, the new patch update on zeromq package contains breaking change 
- Update js-abci
- Downgrade zero mq
Run the tests
None

fix: no patched version of ProtobufJS is used

---

.github/workflows/test_and_release.yml

It should be possible to pass platform test suite scope from the workflow
Add option to specify scope input for `gh-action-run-platform-test-suite` action
In CI

chore(ci): add scope input

---

package-lock.json
package.json

chore: bump version to 0.19.0-dev.7

---

lib/abci/errors/VerboseInternalAbciError.js
lib/abci/handlers/query/verifyChainLockQueryHandlerFactory.js
lib/dpp/DriveStateRepository.js
package-lock.json
package.json
test/unit/abci/handlers/query/verifyChainLockQueryHandlerFactory.spec.js

Verification of chain locks using `verifychainlock` method
- updated `verifyChainLockQueryHandler`
Unit tests, local setup
None.

feat: use Dash Core to verify chain locks

---

package-lock.json
package.json

Updating `dpp` with a fix for feature flags data triggers, as well as `dashcore-lib`
- updated `dpp`
- updated `dashcore-lib`
None.

fix: `topLevelIdentity.getId` is not a function

---

package-lock.json

Updated package-lock file
- Updated package-lock file
Through wallet-lib tests
None

fix: invalid lock file

---

lib/featureFlag/getLatestFeatureFlagFactory.js
test/unit/featureFlag/getLatestFeatureFlagFactory.spec.js

"InvalidQueryError: Invalid query" error during testnet sync process
Do not fetch feature flag contract id on the height it was created 
Unit tests & sync with testnet
No

fix: InvalidQuery error due to feature flags

---

lib/dpp/DriveStateRepository.js
test/unit/dpp/DriveStateRepository.spec.js

Identity create and top up state transitions with Instant Asset Lock Proof are invalidated on `checkTx` if no blocks are produced.
- Validate instant lock with dashcore-lib if there are no blocks produced
With tests
None

fix: invalid instant lock if no blocks are produced

---

.env.example
.github/workflows/.env
lib/createDIContainer.js
lib/validator/ValidatorSet.js
test/unit/validator/ValidatorSet.spec.js

There is a need to configure a specific LLMQ for a specific network (i.e. devnets). Hardcoded selection logic are not flexible enough.
- Introduced required `VALIDATOR_SET_LLMQ_TYPE` env to set validator set LLMQ type
None
- New `VALIDATOR_SET_LLMQ_TYPE` env is required 

feat!: configure validator set LLMQ type

---

package-lock.json
package.json

Version bumped to 0.20.0-dev.5

chore: bump version to 0.20.0-dev.5

---

.github/workflows/test_and_release.yml

Builds were failing with `Error: Process completed with exit code 2.` in case of a cache miss in the release step
- Remove the debug step
In CI
None

ci: remove debug output

---

.github/workflows/test_and_release.yml

The docker metadata action moved
Update metadata action target
in CI
None

ci: update metadata action repo

---

lib/abci/handlers/validator/createValidatorSetUpdate.js
lib/validator/Validator.js

Empty validator pub key object sent even if the public key share is not defined.
- Don't send empty validator pub key
None
None

fix: empty validator pubKey object sent

---

lib/core/errors/QuorumsNotFoundError.js
lib/core/getRandomQuorum.js
test/unit/core/getRandomQuorum.spec.js

Add an error with a detailed message if no quorums were found in the `getRandomQuorum` function
- Add a new error with a detailed context: block hash at which the error appeared, other quorum types in the list if there's any
- Add check to the `getRandomQuorum` so it will throw a new error if no quorums were found
- Through new unit tests
None

feat: add QuorumsNotFoundError fot getRandomQuorum.js when no quorums were found

---

package-lock.json
package.json

chore: bump version to 0.20.0-dev.9

---

package-lock.json
package.json

chore: bump version to 0.20.0-dev.11

---

.dockerignore
docker/cache/.cache/.gitignore
docker/cache/.npm/.gitignore

Remove obsolete docker artifacts from version 0.19
- Remove docker npm cache
- Ignore nyc output from docker context
None
None

build: remove obsolete docker cache dirs

---

.github/workflows/.env
package-lock.json
package.json

chore: bump drive version to v0.20.0-dev.12

---

package-lock.json
package.json

Bump version to 0.20.0-dev.14
Bumped version to 0.20.0-dev.14
None

chore: bump version to 0.20.0-dev.14

---

package-lock.json
package.json

Updating fixed `dapi-grpc` with `height` parameter as `int64`
- updated `dapi-grpc`
None.

fix: height in metadata is uint32 instead of int64

---

package-lock.json
package.json

Need to update DPP to the latest version
DPP was updated to 0.21.0-dev.7
Unit tests
No

chore: update dpp to 0.21.0-dev.7

---

package-lock.json
package.json

Bump version for release
Bump version to 0.21.0-dev.5
In CI
None

chore: bump version to v0.21.0-dev.5
